name: Build

on: [ push ]

jobs:
  build:
    runs-on: ["self-hosted", "macOS"]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant permission to execute
        run: chmod +x gradlew

      - name: Append version name suffix
        id: version
        if: ${{ inputs.versionNameSuffix }} != ''
        run: |
          if grep -q "VERSION_NAME=" gradle.properties; then
            sed -i ' ' "/^VERSION_NAME=/s/$/-tmp-${{ github.run_number }}/" gradle.properties
          else
            echo "Could not find VERSION_NAME in gradle.properties"
            exit 1
          fi

      - name: Build
        run: ./gradlew clean :lib:publishToMavenLocal --console=plain -PubiqueMavenUrl=X -PubiqueMavenUser=X -PubiqueMavenPass=X
