name: Build

on: [ push ]

jobs:
  build:
    runs-on: ["self-hosted", "macOS"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant permission to execute
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean :lib:publishToMavenLocal --console=plain -PubiqueMavenUrl=X -PubiqueMavenUser=X -PubiqueMavenPass=X -PgithubRefName=${{ github.run_number }}-local
