name: Coverage

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  coverage:
    runs-on: ["self-hosted", "macOS"]
    env:
      UB_ARTIFACTORY_URL_ANDROID: x
      UB_ARTIFACTORY_USER: x
      UB_ARTIFACTORY_PASSWORD: x
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant permission to execute
        run: chmod +x gradlew

      - name: Coverage
        run: ./gradlew clean :lib:koverXmlReportJvm --console=plain

      - name: Coverage Report
        uses: mi-kas/kover-report@v1
        with:
          path: lib/build/reports/kover/reportJvm.xml
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 66
          min-coverage-changed-files: 50
          coverage-counter-type: LINE
