name: Publish release artifacts to Artifactory

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ["self-hosted", "macOS"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant permission to execute
        run: chmod +x gradlew

      - name: Publish
        run: ./gradlew :lib:publish -PubiqueMavenUrl=${{secrets.UB_ARTIFACTORY_URL_ANDROID}} -PubiqueMavenUser=${{secrets.UB_ARTIFACTORY_USER}} -PubiqueMavenPass=${{secrets.UB_ARTIFACTORY_PASSWORD}} -PgithubRefName=${{ github.ref_name }}
