name: Publish release artifacts to Artifactory

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    uses: UbiqueInnovation/actions-android/.github/workflows/multiplatform_library_artifactory.yml@v1.5.2
    with:
      libModule: 'lib'
    secrets:
      ANDROID_JENKINS_PAT: ${{ secrets.ANDROID_JENKINS_PAT }}
      UB_ARTIFACTORY_URL_ANDROID: ${{ secrets.UB_ARTIFACTORY_URL_ANDROID }}
      UB_ARTIFACTORY_USERNAME: ${{ secrets.UB_ARTIFACTORY_USERNAME }}
      UB_ARTIFACTORY_PASSWORD: ${{ secrets.UB_ARTIFACTORY_PASSWORD }}
