name: Test

on: [ push ]

jobs:
  test:
    runs-on: ["self-hosted", "macOS"]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant permission to execute
        run: chmod +x gradlew

      - name: Test
        run: ./gradlew clean :lib:jvmTest --console=plain -PubiqueMavenUrl=X -PubiqueMavenUser=X -PubiqueMavenPass=X
