name: Test

on: [ push ]

permissions:
  pull-requests: write
  contents: read
  issues: read
  checks: write

jobs:
  test:
    runs-on: ["self-hosted", "macOS"]
    env:
      UB_ARTIFACTORY_URL_ANDROID: x
      UB_ARTIFACTORY_USER: x
      UB_ARTIFACTORY_PASSWORD: x
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant permission to execute
        run: chmod +x gradlew

      - name: Clean
        run: ./gradlew clean --console=plain

      - name: Tests
        id: tests
        run: ./gradlew :lib:jvmTest --console=plain
        
      - name: Tests Report
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        with:
          check_name: 'Test Results'
          files: lib/build/test-results/**/*.xml
        
      - name: Coverage
        id: coverage
        run: ./gradlew :lib:koverXmlReportJvm --console=plain
        
      - name: Coverage Report
        id: kover
        uses: mi-kas/kover-report@v1
        if: steps.coverage.outcome == 'success'
        with:
          path: | 
            lib/build/reports/kover/report.xml
            lib/build/reports/kover/reportJvm.xml
          title: Code Coverage
          update-comment: true
